name: Sync Github Repos To Gitee

on:
  push:
    branches: 
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.TO_GITEE  }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:HCY2315/python-base.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:hcy_2315/python-base.git
          # 启用后，强制同步，即强制覆盖目的端仓库
          force_update: true
          # 启用后会显示所有执行命令
          debug: true

